### ISSUE TITLE
Can't start the system

### ISSUE THREAD

**Issue by ElizarovEugene** [intel-cloud/cosbench#380]
Hello. Only get acquainted with your project and perhaps something that is not doponyal in the installation, but does not remove the system.
Install Java and Curl, as stated in the documentation.
```
root@ub1404:~/cos# curl -V
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
root@ub1404:~/cos# java -showversion
java version "1.7.0_151"
OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-2ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.151-b01, mixed mode)
```
I'm using Ubuntu 14.04.5 LTS
But after the launch I get the following
```
root@ub1404:~/cos# sh start-all.sh
Launching osgi framwork ...
Successfully launched osgi framework!
Booting cosbench driver ...
...........................................................
Starting    cosbench-log_0.4.2    [ERROR]
...........................................................
Starting    cosbench-tomcat_0.4.2    [ERROR]
...........................................................
Starting    cosbench-config_0.4.2    [ERROR]
...........................................................
Starting    cosbench-http_0.4.2    [ERROR]
...........................................................
Starting    cosbench-cdmi-util_0.4.2    [ERROR]
...........................................................
Starting    cosbench-core_0.4.2    [ERROR]
...........................................................
Starting    cosbench-core-web_0.4.2    [ERROR]
...........................................................
Starting    cosbench-api_0.4.2    [ERROR]
...........................................................
Starting    cosbench-mock_0.4.2    [ERROR]
...........................................................
Starting    cosbench-ampli_0.4.2    [ERROR]
...........................................................
Starting    cosbench-openio_0.4.2    [ERROR]
...........................................................
Starting    cosbench-swift_0.4.2    [ERROR]
...........................................................
Starting    cosbench-keystone_0.4.2    [ERROR]
...........................................................
Starting    cosbench-httpauth_0.4.2    [ERROR]
...........................................................
Starting    cosbench-s3_0.4.2    [ERROR]
...........................................................
Starting    cosbench-oss_0.4.2    [ERROR]
...........................................................
Starting    cosbench-gcs_0.4.2    [ERROR]
...........................................................
Starting    cosbench-librados_0.4.2    [ERROR]
...........................................................
Starting    cosbench-scality_0.4.2    [ERROR]
...........................................................
Starting    cosbench-ecs_0.4.2    [ERROR]
...........................................................
Starting    cosbench-cdmi-swift_0.4.2    [ERROR]
...........................................................
Starting    cosbench-cdmi-base_0.4.2    [ERROR]
...........................................................
Starting    cosbench-driver_0.4.2    [ERROR]
...........................................................
Starting    cosbench-driver-web_0.4.2    [ERROR]
Error in booting cosbench driver!

======================================================

Launching osgi framwork ...
Successfully launched osgi framework!
Booting cosbench controller ...
...........................................................
Starting    cosbench-log_0.4.2    [ERROR]
...........................................................
Starting    cosbench-tomcat_0.4.2    [ERROR]
...........................................................
Starting    cosbench-config_0.4.2    [ERROR]
...........................................................
Starting    cosbench-core_0.4.2    [ERROR]
...........................................................
Starting    cosbench-core-web_0.4.2    [ERROR]
...........................................................
Starting    cosbench-controller_0.4.2    [ERROR]
...........................................................
Starting    cosbench-controller-web_0.4.2    [ERROR]
Error in booting cosbench controller!
```
I looked in log/controller-boot.log and saw
```
root@ub1404:~/cos/log# cat controller-boot.log
Listening on port 0.0.0.0/0.0.0.0:19089 ...
!SESSION 2018-03-23 10:27:57.971 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -console 19089

!ENTRY org.eclipse.osgi 4 0 2018-03-23 10:27:58.364
!MESSAGE Bundle plugins/cosbench-castor not found.

!ENTRY org.eclipse.osgi 4 0 2018-03-23 10:27:58.364
!MESSAGE Bundle plugins/cosbench-log4j not found.

!ENTRY org.eclipse.osgi 4 0 2018-03-23 10:27:58.364
!MESSAGE Bundle plugins/cosbench-log@6:start not found.

!ENTRY org.eclipse.osgi 4 0 2018-03-23 10:27:58.365
!MESSAGE Bundle plugins/cosbench-config@6:start not found.

!ENTRY org.eclipse.osgi 4 0 2018-03-23 10:27:58.365
!MESSAGE Bundle plugins/cosbench-http@6:start not found.

!ENTRY org.eclipse.osgi 4 0 2018-03-23 10:27:58.365
!MESSAGE Bundle plugins/cosbench-tomcat@7:start not found.

!ENTRY org.eclipse.osgi 4 0 2018-03-23 10:27:58.366
!MESSAGE Bundle plugins/cosbench-core@8:start not found.

!ENTRY org.eclipse.osgi 4 0 2018-03-23 10:27:58.366
!MESSAGE Bundle plugins/cosbench-controller@8:start not found.

!ENTRY org.eclipse.osgi 4 0 2018-03-23 10:27:58.366
!MESSAGE Bundle plugins/cosbench-core-web@8:start not found.

!ENTRY org.eclipse.osgi 4 0 2018-03-23 10:27:58.367
!MESSAGE Bundle plugins/cosbench-controller-web@8:start not found.
Persistence bundle starting...
Persistence bundle started.
log4j:WARN No appenders could be found for logger (org.springframework.osgi.extender.internal.boot.ChainActivator).
log4j:WARN Please initialize the log4j system properly.
```
similarly in driver-boot.log
a feeling that something is not installed
what's my mistake? help please understand and start the system

**Comment by rzerda** [comment]
Try 0.4.2 rc4. I'm not shure what's wrong with 0.4.2 release, but rc4 worked and seem to have no major differences from the release version.

**Comment by ElizarovEugene** [comment]
@alexey-dushechkin  Thanks, I'll try later.

**Comment by vpadronblanco** [comment]
Seems like there is no right answer as to which version to use. I am running it on an EC2 instance so Desktop UI is not that easy to set up. And also, 0.4.2 c4 cannot have MD5 check, as stated in other issues. Any pointers on how to fix this?

**Comment by keirafadams** [comment]
I'm seeing very similar issues as @ElizarovEugene, for what its worth.

**Comment by Nathaniel7687** [comment]
My pull request version(#373) is solved this problem and this issue already reported(#372).
You can use it(https://github.com/Nathaniel7687/cosbench).

**Comment by keirafadams** [comment]
@Nathaniel7687 For what its worth I did try to use your fork, however the issue remained. I found that cosbench seems to have problems with Openjdk-jre-9, reverting to 8 removed the issue.

**Comment by DeniseK21** [comment]
I am running Ubuntu 16.04
java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

I am experiencing the same issue

**Comment by Nathaniel7687** [comment]
> I am running Ubuntu 16.04
> java -version
> openjdk version "1.8.0_191"
> OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
> OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
> 
> I am experiencing the same issue

@DeniseK21
According to the cosbench user guide, they are recommending to use jdk version 7.
In my experience, cosbench doesn't work with jdk 8 or later.
You must operate cosbench with jdk version 7.

**Comment by DeniseK21** [comment]
I uninstalled JDK 8 and installed JDK 7 and  unfortunately still experiencing the same issue.
root@cosbox01:~/cos# java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-3)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**Comment by TangWu5912** [comment]
I have the same issue and retried many times. It may be due to residual processes in your previous installation, you can use 'ps -ef |grep cosbench' and kill all of them, then reinstall to solve it
